name: Deploy

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - run: | # TODO: Replace with your build steps
          mkdir data
          echo "<h1>Hello Yoru Pages!</h1>" > data/index.html

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: data

  deploy:
    runs-on: ubuntu-latest

    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: write
      id-token: write
      pages: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        id: deployment
